// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: discovery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeManager_HandoverPeers_FullMethodName = "/kuberbolt.discovery.v1.NodeManager/HandoverPeers"
)

// NodeManagerClient is the client API for NodeManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────────────
// NodeManager — discovery-layer service.
//
// The Python SDK ("scout") discovers peer endpoints (currently hardcoded
// dummies; Nostr relay integration comes later) and hands them to the Go
// daemon ("engine") via this RPC.
// ──────────────────────────────────────────────────────────────────────────────
type NodeManagerClient interface {
	// HandoverPeers delivers discovered peer endpoints to the engine.
	// For the bootstrap phase this is fire-and-forget: the engine logs the
	// endpoints and returns an ack.  Real processing logic will be added later.
	HandoverPeers(ctx context.Context, in *PeerHandoverRequest, opts ...grpc.CallOption) (*PeerHandoverResponse, error)
}

type nodeManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeManagerClient(cc grpc.ClientConnInterface) NodeManagerClient {
	return &nodeManagerClient{cc}
}

func (c *nodeManagerClient) HandoverPeers(ctx context.Context, in *PeerHandoverRequest, opts ...grpc.CallOption) (*PeerHandoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerHandoverResponse)
	err := c.cc.Invoke(ctx, NodeManager_HandoverPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeManagerServer is the server API for NodeManager service.
// All implementations must embed UnimplementedNodeManagerServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────────────
// NodeManager — discovery-layer service.
//
// The Python SDK ("scout") discovers peer endpoints (currently hardcoded
// dummies; Nostr relay integration comes later) and hands them to the Go
// daemon ("engine") via this RPC.
// ──────────────────────────────────────────────────────────────────────────────
type NodeManagerServer interface {
	// HandoverPeers delivers discovered peer endpoints to the engine.
	// For the bootstrap phase this is fire-and-forget: the engine logs the
	// endpoints and returns an ack.  Real processing logic will be added later.
	HandoverPeers(context.Context, *PeerHandoverRequest) (*PeerHandoverResponse, error)
	mustEmbedUnimplementedNodeManagerServer()
}

// UnimplementedNodeManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeManagerServer struct{}

func (UnimplementedNodeManagerServer) HandoverPeers(context.Context, *PeerHandoverRequest) (*PeerHandoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandoverPeers not implemented")
}
func (UnimplementedNodeManagerServer) mustEmbedUnimplementedNodeManagerServer() {}
func (UnimplementedNodeManagerServer) testEmbeddedByValue()                     {}

// UnsafeNodeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeManagerServer will
// result in compilation errors.
type UnsafeNodeManagerServer interface {
	mustEmbedUnimplementedNodeManagerServer()
}

func RegisterNodeManagerServer(s grpc.ServiceRegistrar, srv NodeManagerServer) {
	// If the following call panics, it indicates UnimplementedNodeManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeManager_ServiceDesc, srv)
}

func _NodeManager_HandoverPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerHandoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagerServer).HandoverPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManager_HandoverPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagerServer).HandoverPeers(ctx, req.(*PeerHandoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeManager_ServiceDesc is the grpc.ServiceDesc for NodeManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuberbolt.discovery.v1.NodeManager",
	HandlerType: (*NodeManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandoverPeers",
			Handler:    _NodeManager_HandoverPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
